const bcrypt = require('bcrypt');

module.exports = {
  up: queryInterface => queryInterface.bulkInsert(
    'Users',
    [
      {
        id: 1,
        name: 'Steve Jobs',
        username: 'ceo',
        provinceId: 12,
        password: bcrypt.hashSync('ceo', 10),
      },
      {
        id: 2,
        name: 'Steve Wozniack',
        username: 'manager',
        provinceId: 12,
        password: bcrypt.hashSync('manager', 10),
      },
      {
        id: 3,
        name: 'John Nash',
        username: 'accountant',
        provinceId: 12,
        password: bcrypt.hashSync('accountant', 10),
      },
      {
        id: 4,
        name: 'John Sculley',
        username: 'owner',
        provinceId: 12,
        password: bcrypt.hashSync('owner', 10),
      },
      {
        id: 5,
        name: 'Operator',
        username: 'operator',
        provinceId: 12,
        password: bcrypt.hashSync('operator', 10),
      },
      {
        id: 6,
        name: 'Sales Manager',
        username: 'sales',
        provinceId: 12,
        password: bcrypt.hashSync('sales', 10),
      },
      {
        id: 7,
        name: 'Абдуллаев Д.',
        username: 'davron',
        provinceId: 12,
        password: bcrypt.hashSync('davron', 10),
      },
      {
        id: 8,
        name: 'Алтынбеков Р.',
        username: 'altinbekov',
        provinceId: 12,
        password: bcrypt.hashSync('altinbekov', 10),
      },
      {
        id: 9,
        name: 'Аракулов Д.',
        username: 'doniyor',
        provinceId: 12,
        password: bcrypt.hashSync('doniyor', 10),
      },
      {
        id: 10,
        name: 'Газизов И.',
        username: 'ildar',
        provinceId: 12,
        password: bcrypt.hashSync('ildar', 10),
      },
      {
        id: 11,
        name: 'Джураев С.',
        username: 'sanjar',
        provinceId: 12,
        password: bcrypt.hashSync('sanjar', 10),
      },
      {
        id: 12,
        name: 'Замалетдинова А.',
        username: 'alfiya',
        provinceId: 12,
        password: bcrypt.hashSync('alfiya', 10),
      },
      {
        id: 13,
        name: 'Мирзаев К.',
        username: 'kurbon',
        provinceId: 12,
        password: bcrypt.hashSync('kurbon', 10),
      },
      {
        id: 14,
        name: 'Нусеров Р.',
        username: 'nuserov',
        provinceId: 12,
        password: bcrypt.hashSync('nuserov', 10),
      },
      {
        id: 15,
        name: 'Нусеров Рустам.',
        username: 'rustam',
        provinceId: 12,
        password: bcrypt.hashSync('rustam', 10),
      },
      {
        id: 16,
        name: 'Орипов А.',
        username: 'ahmatxuja',
        provinceId: 12,
        password: bcrypt.hashSync('ahmatxuja', 10),
      },
      {
        id: 17,
        name: 'Сили Н.',
        username: 'nailya',
        provinceId: 12,
        password: bcrypt.hashSync('nailya', 10),
      },
    ],
    {},
  ),

  down: queryInterface => queryInterface.bulkDelete('Users', null, {}),
};
